cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker ps -q --filter ancestor="gitlab-runner/evonne" | xargs -r docker stop
    - docker build . -t gitlab-runner/evonne
    - docker run -dp 7007:3000 gitlab-runner/evonne:latest
  tags:
    - node
